---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(TableOneDataframe)
data(mtcars)
```


```{r}
# Making the stata variable a factor
mtcars$cyl <- factor(mtcars$cyl)
levels(mtcars$cyl) <- c("4", "6", "8", "Extra")
```

```{r}
# Creating an empty output table to store results. Make sure the 'strata' variable is a factor.
# Empty levels get a separate column.
# The include_tests argument determines if all of the functions after do p-value testing.
output <- make_output_df(mtcars, "cyl", include_tests = TRUE)
# Median IQR
output <- get_median_iqr(mtcars, 'cyl', 'disp', "Display", output)
# Mean (SD)
output <- get_mean_sd(mtcars, 'cyl', 'hp', "HP", output)

# Count
output <- get_count(mtcars, 'cyl', 'wt', "WT", output)

# N %
# Adding a random NA to demonstrate. 
mtcars[3, 'gear'] <- NA
# We want to treat gears as a factor rather than a number
mtcars$gear <- as.factor(mtcars$gear)
output <- get_n_percent(mtcars, 'cyl', 'gear', "Gear", output)

# If it's not a factor, gets converted anyway.
output <- get_n_percent(mtcars, 'cyl', 'carb', "Carb", output)

# Output is just a dataframe, so can be used with kable, or written to excel/csv.
```
